### ISSUE TITLE
Redmine 3.x compatibility

### ISSUE THREAD

**Issue by ppoektos** [raafael911/multi_time_tracker#14]
Are you planning to do it?

**Comment by raafael911** [comment]
I will have a look at it in the next two weeks. Currently I'm busy with my thesis.

**Comment by raafael911** [comment]
The plugin should now be compatible to Redmine 3.x. Please let me know if you encounter any troubles.

**Comment by ppoektos** [comment]
Thank you, I'll test and report back.

On Wed, Jun 3, 2015 at 10:29 AM, Kevin Neuenfeldt <notifications@github.com>
wrote:

> The plugin should now be compatible to Redmine 3.x. Please let me know if
> you encounter any troubles.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/raafael911/multi_time_tracker/issues/14#issuecomment-108246259>
> .
>



-- 

Best / С наилучшими пожеланиями


 *Pavel Potcheptsov*

   LLC EKTOS-Ukraine

System administrator

   1, Academika Proskury

Mobile UA: +38 050 3642391

Home UA: +380 572 931115

   61070 Kharkiv

   www.ektos.com.ua <http://www.ektos.net/>

E-mail:

ppo@ektos.net


  Skype:      potcheptsov.pavel

**Comment by ppoektos** [comment]
[root@redmine rm303]# rake redmine:plugins:migrate RAILS_ENV=production
Migrating advanced_roadmap_v2 (Advanced roadmap & milestones plugin)...
Migrating multi_time_tracker (Multi Time Tracker)...
== 1 CreateLoggedTimes: migrating
=============================================
-- create_table(:logged_times)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: BLOB/TEXT column 'comment' can't have a default value:
CREATE TABLE `logged_times` (`id` int(11) auto_increment PRIMARY KEY,
`user_id` int(11) NOT NULL, `project_id` int(11) NOT NULL, `issue_id`
int(11) NOT NULL, `activity_id` int(11), `comment` text DEFAULT '',
`active` tinyint(1) NOT NULL, `activated_at` datetime, `spent_seconds`
int(11) DEFAULT 0)
ENGINE=InnoDB/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in
`query'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in
`block in execute'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:473:in
`block in log'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in
`instrument'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:467:in
`log'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in
`execute'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in
`execute'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:208:in
`create_table'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:462:in
`create_table'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in
`block in method_missing'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in
`block in say_with_time'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in
`say_with_time'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/migration.rb:652:in
`method_missing'
/var/www/rm303/plugins/multi_time_tracker/db/migrate/001_create_logged_times.rb:3:in
`change'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/migration.rb:606:in
`exec_migration'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in
`block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in
`block in migrate'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in
`with_connection'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in
`migrate'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in
`migrate'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in
`block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/migration.rb:1043:in
`ddl_transaction'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in
`execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in
`block in migrate'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in
`each'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in
`migrate'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in
`up'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in
`migrate'
/var/www/rm303/lib/redmine/plugin.rb:474:in `migrate_plugin'
/var/www/rm303/lib/redmine/plugin.rb:446:in `migrate'
/var/www/rm303/lib/redmine/plugin.rb:460:in `block in migrate'
/var/www/rm303/lib/redmine/plugin.rb:459:in `each'
/var/www/rm303/lib/redmine/plugin.rb:459:in `migrate'
/var/www/rm303/lib/tasks/redmine.rake:127:in `block (3 levels) in <top
(required)>'
/usr/local/rvm/gems/ruby-1.9.3-p327/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p327/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

On Wed, Jun 3, 2015 at 10:39 AM, Pavel Potcheptsov (EKTOS) <ppo@ektos.net>
wrote:

> Thank you, I'll test and report back.
>
> On Wed, Jun 3, 2015 at 10:29 AM, Kevin Neuenfeldt <
> notifications@github.com> wrote:
>
>> The plugin should now be compatible to Redmine 3.x. Please let me know if
>> you encounter any troubles.
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/raafael911/multi_time_tracker/issues/14#issuecomment-108246259>
>> .
>>
>
>
>
> --
>
> Best / С наилучшими пожеланиями
>
>
>  *Pavel Potcheptsov*
>
>    LLC EKTOS-Ukraine
>
> System administrator
>
>    1, Academika Proskury
>
> Mobile UA: +38 050 3642391
>
> Home UA: +380 572 931115
>
>    61070 Kharkiv
>
>    www.ektos.com.ua <http://www.ektos.net/>
>
> E-mail:
>
> ppo@ektos.net
>
>
>   Skype:      potcheptsov.pavel
>



-- 

Best / С наилучшими пожеланиями


 *Pavel Potcheptsov*

   LLC EKTOS-Ukraine

System administrator

   1, Academika Proskury

Mobile UA: +38 050 3642391

Home UA: +380 572 931115

   61070 Kharkiv

   www.ektos.com.ua <http://www.ektos.net/>

E-mail:

ppo@ektos.net


  Skype:      potcheptsov.pavel

**Comment by raafael911** [comment]
That's an interesting behaviour. You are using a Windows server, right? To fix this you can open db/migrate/001_create_logged_times.rb and change the line
t.text :comment, :default => ""
to
t.text :comment

MySQL servers on Windows don't accept default values for text columns for some reason.

**Comment by raafael911** [comment]
Please let me know if this works for you

**Comment by ppoektos** [comment]
No. I use CentOS 6.3 for Redmine and Debian for MySQL 5.1.73-1

On Wed, Jun 3, 2015 at 11:48 AM, Kevin Neuenfeldt <notifications@github.com>
wrote:

> Please let me know if this works for you
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/raafael911/multi_time_tracker/issues/14#issuecomment-108277493>
> .
>



-- 

Best / С наилучшими пожеланиями


 *Pavel Potcheptsov*

   LLC EKTOS-Ukraine

System administrator

   1, Academika Proskury

Mobile UA: +38 050 3642391

Home UA: +380 572 931115

   61070 Kharkiv

   www.ektos.com.ua <http://www.ektos.net/>

E-mail:

ppo@ektos.net


  Skype:      potcheptsov.pavel

**Comment by ppoektos** [comment]
But I changed migration as you said and now migration finished.
I'll let my users know that this plugin available now and report back if
get any problem.

On Wed, Jun 3, 2015 at 12:33 PM, Pavel Potcheptsov (EKTOS) <ppo@ektos.net>
wrote:

> No. I use CentOS 6.3 for Redmine and Debian for MySQL 5.1.73-1
>
> On Wed, Jun 3, 2015 at 11:48 AM, Kevin Neuenfeldt <
> notifications@github.com> wrote:
>
>> Please let me know if this works for you
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/raafael911/multi_time_tracker/issues/14#issuecomment-108277493>
>> .
>>
>
>
>
> --
>
> Best / С наилучшими пожеланиями
>
>
>  *Pavel Potcheptsov*
>
>    LLC EKTOS-Ukraine
>
> System administrator
>
>    1, Academika Proskury
>
> Mobile UA: +38 050 3642391
>
> Home UA: +380 572 931115
>
>    61070 Kharkiv
>
>    www.ektos.com.ua <http://www.ektos.net/>
>
> E-mail:
>
> ppo@ektos.net
>
>
>   Skype:      potcheptsov.pavel
>



-- 

Best / С наилучшими пожеланиями


 *Pavel Potcheptsov*

   LLC EKTOS-Ukraine

System administrator

   1, Academika Proskury

Mobile UA: +38 050 3642391

Home UA: +380 572 931115

   61070 Kharkiv

   www.ektos.com.ua <http://www.ektos.net/>

E-mail:

ppo@ektos.net


  Skype:      potcheptsov.pavel

**Comment by raafael911** [comment]
Great, thank you.
