### ISSUE TITLE
error on rake redmine:plugins:migrate RAILS_ENV=production

### ISSUE THREAD

**Issue by rnsokolov** [raafael911/multi_time_tracker#15]
redmine v3.0.3

== 1 CreateLoggedTimes: migrating =============================================
-- create_table(:logged_times)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: BLOB/TEXT column 'comment' can't have a default value: CREATE TABLE `logged_times` (`id` int(11) auto_increment PRIMARY KEY, `user_id` int(11) NOT NULL, `project_id` int(11) NOT NULL, `issue_id` int(11) NOT NULL, `activity_id` int(11), `comment` text DEFAULT '', `active` tinyint(1) NOT NULL, `activated_at` datetime, `spent_seconds` int(11) DEFAULT 0) ENGINE=InnoDB/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `query'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `block in execute'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/usr/local/share/gems/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `execute'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:208:in `create_table'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:462:in `create_table'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in `block in method_missing'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `block in say_with_time'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `say_with_time'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:652:in `method_missing'
/var/www/redmine/plugins/multi_time_tracker/db/migrate/001_create_logged_times.rb:3:in `change'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:606:in `exec_migration'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:1043:in `ddl_transaction'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/var/www/redmine/lib/redmine/plugin.rb:474:in `migrate_plugin'
/var/www/redmine/lib/redmine/plugin.rb:446:in `migrate'
/var/www/redmine/lib/redmine/plugin.rb:460:in `block in migrate'
/var/www/redmine/lib/redmine/plugin.rb:459:in `each'
/var/www/redmine/lib/redmine/plugin.rb:459:in `migrate'
/var/www/redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
[

**Comment by ppoektos** [comment]
https://github.com/raafael911/multi_time_tracker/issues/14

On Thu, Jun 4, 2015 at 3:41 PM, Roman <notifications@github.com> wrote:

> == 1 CreateLoggedTimes: migrating
> =============================================
> -- create_table(:logged_times)
> rake aborted!
> StandardError: An error has occurred, all later migrations canceled:
>
> Mysql2::Error: BLOB/TEXT column 'comment' can't have a default value:
> CREATE TABLE logged_times (id int(11) auto_increment PRIMARY KEY, user_id
> int(11) NOT NULL, project_id int(11) NOT NULL, issue_id int(11) NOT NULL,
> activity_id int(11), comment text DEFAULT '', active tinyint(1) NOT NULL,
> activated_at datetime, spent_seconds int(11) DEFAULT 0)
> ENGINE=InnoDB/usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in
> query'
>
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:inblock
> in execute'
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:473:in
> block in log'
>
> /usr/local/share/gems/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in
> instrument'
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:467:in
> log'
>
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in
> execute'
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in
> execute'
>
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:208:in
> create_table'
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:462:in
> create_table'
>
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:inblock
> in method_missing'
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in
> block in say_with_time'
>
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in
> say_with_time'
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:652:in
> method_missing'
>
> /var/www/redmine/plugins/multi_time_tracker/db/migrate/001_create_logged_times.rb:3:in
> change'
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:606:in
> exec_migration'
>
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:inblock
> (2 levels) in migrate'
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in
> block in migrate'
>
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in
> with_connection'
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in
> migrate'
>
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in
> migrate'
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in
> block in execute_migration_in_transaction'
>
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:1043:in
> ddl_transaction'
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in
> execute_migration_in_transaction'
>
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:inblock
> in migrate'
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in
> each'
>
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in
> migrate'
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in
> up'
>
> /usr/local/share/gems/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in
> migrate'
> /var/www/redmine/lib/redmine/plugin.rb:474:in migrate_plugin'
> /var/www/redmine/lib/redmine/plugin.rb:446:inmigrate'
> /var/www/redmine/lib/redmine/plugin.rb:460:in block in migrate'
> /var/www/redmine/lib/redmine/plugin.rb:459:ineach'
> /var/www/redmine/lib/redmine/plugin.rb:459:in migrate'
> /var/www/redmine/lib/tasks/redmine.rake:127:inblock (3 levels) in '
> Tasks: TOP => redmine:plugins:migrate
> (See full trace by running task with --trace)
> [
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/raafael911/multi_time_tracker/issues/15>.
>



-- 

Best / С наилучшими пожеланиями


 *Pavel Potcheptsov*

   LLC EKTOS-Ukraine

System administrator

   1, Academika Proskury

Mobile UA: +38 050 3642391

Home UA: +380 572 931115

   61070 Kharkiv

   www.ektos.com.ua <http://www.ektos.net/>

E-mail:

ppo@ektos.net


  Skype:      potcheptsov.pavel

**Comment by raafael911** [comment]
Yes, thank you. I have totally forgotten to push this fix.
